#!/bin/bash
sed '/<tr>/,/<\/td>/d' |
tr '[:upper:]' '[:lower:]' |
sed 's/<u>\(.\)<\/u>/\1/g' |
sed "s/\`/\'/g" |
sed -n '/<td>/,/<\/td>/p' |
sed '/<\/tr>/d' |
sed 's/^\s*<td>\(.*\)<\/td>/\1/' |
sed 's/\s/</g' |
sed 's/,/</g' |
sed 's/</\n/g' |
sed '/^\s*$/d' |
sed "/[pk\'mnwlhaeiou]/!d" |
sort -u 
 
