#!/bin/bash
dir=$1
RESULT="$(ls -a $dir)"
#echo $RESULT
declare -a ARRAY 	
let count=0
for FILE in $RESULT
do	
	if [ ! -L "$dir/$FILE" ] && [ -f "$dir/$FILE" ]
	then
		ARRAY[$count]="$dir/$FILE"
		let count+=1
	fi
done

for FIRST in "${ARRAY[@]}"
do
	for SECOND in "${ARRAY[@]}"
	do
		if [[ "$FIRST" != "$SECOND" ]]
		then			
			if [[ "$FIRST" < "$SECOND" ]]		
			then
				if cmp "$FIRST" "$SECOND" 
				then
					rm $SECOND
					echo $FIRST $SECOND	
					ln $FIRST $SECOND		
				fi
			fi
		fi
	done
done
	

